import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { getServerSession } from '@/lib/auth'
import Link from 'next/link'
import { getUserFromSession } from '@/models/user'
import { redirect } from 'next/navigation'

import { config } from '@fortawesome/fontawesome-svg-core'
import '@fortawesome/fontawesome-svg-core/styles.css'
config.autoAddCss = false

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const session = await getServerSession()
  const signedIn = !!session
  if (signedIn && !session.user?.email) {
    redirect('/api/auth/signout')
  }
  const userData = await getUserFromSession(session)

  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header>
          <div className='flex items-center gap-4 p-8'>
            <Link href='/' className='text-4xl font-bold text-orange-500'>
              BeavCode
            </Link>
            <div className='ml-auto mr-0'>
              {userData ? (
                <>
                  {userData?.streakCount ? <span>{userData.streakCount} Week Streak</span> : undefined}
                  <Link
                    href='/api/auth/signout'
                    className='inline-flex h-8 items-center justify-center rounded-md border border-foreground px-2 text-sm font-medium text-foreground hover:bg-foreground/10'
                  >
                    Sign Out
                  </Link>
                  {/* <Image src={session.user?.image || '/default-avatar.png'} alt='Profile' width={40} height={40} className='rounded-full' /> */}
                </>
              ) : (
                <Link
                  href='/api/auth/signin'
                  className='inline-flex h-8 items-center justify-center rounded-md border border-foreground px-2 text-sm font-medium text-foreground hover:bg-foreground/10'
                >
                  Sign In
                </Link>
              )}
            </div>
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
