services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: ${PG_PASS}
      PGDATA: /data/postgres
      POSTGRES_DB: beavcode
    volumes:
      - db:/data/postgres
    restart: unless-stopped
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d beavcode']
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - '5432:5432'
  pyrunner:
    build: ./pyrunner/
    deploy:
      resources:
        limits:
          cpus: '0.1'
  web-app:
    container_name: web-app
    build: ./web-app/
    # ports:
    #   - '3000:3000'
    # depends_on:
    #   db:
    #     condition: service_healthy
    #     restart: true
    # pyrunner:
    #   condition: service_started
  proxy:
    container_name: proxy
    build: ./nginx
    ports:
      - '443:443'

volumes:
  db:
