# FROM python:alpine3.21
FROM ubuntu:latest
ENV development="true"
ENV PYDEVD_DISABLE_FILE_VALIDATION=1

# Install packages
RUN apt-get update -y
RUN apt-get install python3 python3-pip debootstrap -y

# Sandbox setup
# Create chroot jail
WORKDIR /home
RUN mkdir run_env
RUN debootstrap focal run_env
RUN chroot run_env /bin/bash -c "adduser --disabled-password --home /home  --gecos \"\" sandbox"
RUN chroot run_env /bin/bash -c "apt-get install software-properties-common -y"
RUN chroot run_env /bin/bash -c "add-apt-repository universe && apt-get update -y && apt-get install python3-pip -y && pip3 install memory_profiler"
WORKDIR /home/run_env/home
COPY run_env/wrapper.py ./
RUN touch output.json

WORKDIR /home/run_env
RUN chmod -R 775 home 
RUN chmod 666 home/output.json

# Server setup
WORKDIR /home/server
# Server dependencies, source code
COPY requirements.txt ./
RUN pip install --no-cache-dir --break-system-packages -r requirements.txt
COPY server/server.py ./
COPY server/exec_test.sh ./

WORKDIR /home
RUN chmod 770 -R server

WORKDIR /home/server
EXPOSE 3001

CMD ["python3", "server.py"]